before:
  hooks:
    - go mod tidy
builds:
  - env:
    - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - > 
        -s -w
        -X {{ .ModulePath }}/vars.ProjectName={{ .ProjectName }} 
        -X {{ .ModulePath }}/vars.BuildVersion={{ .Version }} 
        -X {{ .ModulePath }}/vars.BuildRevision={{ .ShortCommit }} 
        -X {{ .ModulePath }}/vars.BuildDate={{ .Date }} 
        -X {{ .ModulePath }}/vars.ProjectDocs={{ .GitURL }}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      # Linux only:
      # arm 8
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm64
      # arm 6
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: windows
        goarch: arm
    binary: '{{ .ProjectName }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
